name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:lts-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Version
        run: node -v